set(VCPKG_TARGET_ARCHITECTURE arm64ec)
set(VCPKG_PLATFORM_TOOLSET_VERSION 14.38)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_C_FLAGS "/guard:cf /Qspectre /arm64EC")
set(VCPKG_CXX_FLAGS "/guard:cf /Qspectre /arm64EC")
set(VCPKG_LINK_FLAGS "/MACHINE:ARM64EC")
set(VCPKG_LINKER_FLAGS "/guard:cf /DYNAMICBASE")

set(VCPKG_ENV_PASSTHROUGH "__VCVARSALL_SPECTRE")

# OpenSSL-specific flags
set(OPENSSL_USE_NOPINSHARED ON)
set(OPENSSL_NO_ASM OFF)

# opentelemetry
set(CMAKE_SYSTEM_PROCESSOR arm64ec)

set(VCPKG_CMAKE_CONFIGURE_OPTIONS
    -DBOOST_CONTEXT_NO_ASM=ON
)
